# Generated by Django 5.1.4 on 2025-07-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='geohash',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
