# Generated by Django 5.1.4 on 2025-03-06 23:06

import django.contrib.gis.db.models.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(choices=[('RADAR', 'Radar'), ('CAMERA', 'Camera')], max_length=12)),
                ('direction', models.CharField(choices=[('+', 'Crescent'), ('-', 'Decreasing'), ('*', 'Both')], max_length=2)),
                ('latitude', models.CharField()),
                ('longitude', models.CharField()),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, geography=True, null=True, srid=4326)),
                ('road', models.CharField()),
            ],
            options={
                'ordering': ('type', 'road'),
            },
        ),
        migrations.CreateModel(
            name='LowEmissionZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('city', models.CharField()),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('restrictions', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
