# Generated by Django 5.1.4 on 2025-04-30 23:46

import commons.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmation_code',
            field=models.CharField(default=commons.utils.generate_confirmation_code, max_length=6),
        ),
    ]
