# Generated by Django 5.1.4 on 2025-06-01 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_reserved_by'),
        ('spaces', '0004_alter_paidspace_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='spaces.paidspace'),
        ),
    ]
