# Generated by Django 5.1.4 on 2025-07-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_by_user_email',
            field=models.CharField(blank=True, null=True),
        ),
    ]
