# Generated by Django 5.1.4 on 2025-04-22 21:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('legal_first_name', models.CharField(max_length=200)),
                ('legal_last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('term_of_service', models.JSONField()),
                ('status', models.CharField(choices=[('MISSING_INFO', 'Missing info'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='MISSING_INFO', max_length=20)),
                ('step', models.CharField(choices=[('PERSONAL_INFO', 'Personal info'), ('ADDRESS_INFO', 'Address info'), ('DOCUMENT_INFO', 'Document info'), ('BANK_ACCOUNT_INFO', 'Bank account info'), ('SUBMITTED', 'Submitted')], default='PERSONAL_INFO', max_length=20)),
                ('provider_id', models.CharField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earning_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountIDDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('front_side_token', models.CharField()),
                ('back_side_token', models.CharField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='credits.earningaccount')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('country', models.CharField()),
                ('currency', models.CharField()),
                ('account_holder_name', models.CharField()),
                ('account_number', models.CharField()),
                ('provider_id', models.CharField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='credits.earningaccount')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('full_street', models.CharField()),
                ('city', models.CharField()),
                ('postal_code', models.CharField()),
                ('country', models.CharField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='credits.earningaccount')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
