# Generated by Django 5.1.4 on 2025-04-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbankaccount',
            old_name='provider_id',
            new_name='payment_provider_id',
        ),
        migrations.RenameField(
            model_name='earningaccount',
            old_name='provider_id',
            new_name='payment_provider_id',
        ),
        migrations.AddField(
            model_name='accountbankaccount',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='earningaccount',
            name='country',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
    ]
