# Generated by Django 5.1.4 on 2025-04-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_rename_provider_id_accountbankaccount_payment_provider_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountiddocument',
            name='document_type',
            field=models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('RESIDENT_PERMIT', 'Resident Permit')], default='NATIONAL_ID', max_length=20),
        ),
        migrations.AlterField(
            model_name='earningaccount',
            name='status',
            field=models.CharField(choices=[('MISSING_INFO', 'Missing info'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('BLOCKED', 'Blocked'), ('ACCEPTED', 'Accepted')], default='MISSING_INFO', max_length=20),
        ),
    ]
