# Generated by Django 5.1.4 on 2025-04-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_accountiddocument_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
