# Generated by Django 5.1.4 on 2025-04-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_earningaccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningaccount',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
