# Generated by Django 5.1.4 on 2025-04-30 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0006_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='token',
        ),
    ]
