# Generated by Django 5.1.4 on 2025-05-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0007_remove_paymentmethod_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningaccount',
            name='pending_balance',
            field=models.IntegerField(default=0),
        ),
    ]
