# Generated by Django 5.1.4 on 2025-05-02 22:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0009_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('country', models.CharField()),
                ('currency', models.CharField()),
                ('account_holder_name', models.CharField()),
                ('account_number', models.CharField()),
                ('is_default', models.BooleanField(default=False)),
                ('payment_provider_id', models.CharField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to='credits.earningaccount')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AccountBankAccount',
        ),
    ]
