# Generated by Django 5.1.4 on 2025-05-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0011_remove_transaction_user_transaction_account_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='expiration_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
