# Generated by Django 5.1.4 on 2025-05-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0012_paymentmethod_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningaccount',
            name='available_balance',
            field=models.IntegerField(default=0),
        ),
    ]
