# Generated by Django 5.1.4 on 2025-06-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0013_earningaccount_available_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_provider_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
