# Generated by Django 5.1.4 on 2025-03-08 15:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('available_spaces', models.BooleanField(default=True)),
                ('radar_alert', models.BooleanField(default=True)),
                ('camera_alert', models.BooleanField(default=True)),
                ('prohibited_zone_alert', models.BooleanField(default=True)),
                ('speed_limit_alert', models.BooleanField(default=True)),
                ('fatigue_alert', models.BooleanField(default=True)),
                ('police_alert', models.BooleanField(default=True)),
                ('accident_alert', models.BooleanField(default=True)),
                ('road_closed_alert', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=True)),
                ('push', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
