# Generated by Django 5.1.4 on 2025-03-09 17:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userpreferences_user'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='action',
            field=models.CharField(choices=[('SPACE_CREATED', 'Space created'), ('SPACE_OCCUPIED', 'Space occupied'), ('SPACE_NOT_VALID', 'Space not valid'), ('SPACE_IN_USE', 'Space in use'), ('EVENT_CREATED', 'Event created'), ('POLICE', 'Event police'), ('CLOSED_ROAD', 'Event closed road'), ('ACCIDENT', 'Event accident'), ('FEEDBACK', 'User feedback')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('read', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('SPACE_OCCUPIED', 'Space occupied'), ('SPACE_RESERVED', 'Space reserved'), ('SPACE_NEARBY', 'Space nearby')], max_length=15)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
