# Generated by Django 5.1.4 on 2025-04-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userdevice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='en', max_length=2),
        ),
    ]
