# Generated by Django 5.1.4 on 2025-04-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_provider_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
