# Generated by Django 5.1.4 on 2025-04-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_payment_provider_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='payment_provider_id',
            new_name='provider_customer_id',
        ),
    ]
