# Generated by Django 5.1.4 on 2025-03-06 22:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import spaces.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(choices=[('FREE', 'Free'), ('DISABLED', 'Disabled'), ('BLUE', 'Blue'), ('GREEN', 'Green')], max_length=10)),
                ('image', models.ImageField(upload_to=spaces.models.unique_upload_path)),
                ('street_name', models.CharField()),
                ('latitude', models.CharField()),
                ('longitude', models.CharField()),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, geography=True, null=True, srid=4326)),
                ('expires_at', models.DateTimeField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreeSpace',
            fields=[
                ('basespace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spaces.basespace')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
            bases=('spaces.basespace',),
        ),
    ]
