# Generated by Django 5.1.4 on 2025-04-12 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_spacefeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidSpace',
            fields=[
                ('basespace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spaces.basespace')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('phone', models.CharField()),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
            bases=('spaces.basespace',),
        ),
    ]
