# Generated by Django 5.1.4 on 2025-04-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_paidspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidspace',
            name='price',
            field=models.IntegerField(),
        ),
    ]
